name:Cypress Tests
on: [push]
jobs: 
  cypress-run:
    runs-on: Windows 10 Pro
    steps:
     -name: Checkout
       uses: actions/checkout@v2
       -name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start

